name: fusioncrds_app
description: A Flutter app to detect location & list nearby merchants.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # maps & location
  flutter_map: ^4.0.0
  latlong2: ^0.8.1
  geolocator: ^9.0.2

  # API & config
  http: ^0.13.5
  flutter_dotenv: ^5.0.2
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/merchant_illustration.png
